### ISSUE TITLE
Empty DeviceList for HP Photosmart 7520

### ISSUE THREAD

**Issue by tiriki** [sjamesr/jfreesane#27]
While `scanimage -L` gives me:

`device `hpaio:/net/Photosmart_7520_series?ip=192.168.0.3' is a Hewlett-Packard Photosmart_7520_series all-in-one`

the code:

``` java
session = SaneSession.withRemoteSane(InetAddress.getLocalHost());
List<SaneDevice> devices = session.listDevices(); 
```

returns just an empty list.

Using jfreesane 0.95 (in maven).

**Comment by sjamesr** [comment]
I think that when you do `scanimage -L`, the entry you get back is not from the sane daemon but is coming directly from the sane backend built into the scanimage command. Can you double-check that your sane server is setup correctly?

**Comment by sjamesr** [comment]
I would expect if the sane daemon were working properly, `scanimage -L` should give you two entries. For example, in my setup:

```
$ scanimage -L 
device `pixma:MX7600_192.168.2.107' is a CANON Canon PIXMA MX7600 multi-function peripheral
device `net:localhost:pixma:MX7600_192.168.2.107' is a CANON Canon PIXMA MX7600 multi-function peripheral
```

The second line is from the `net` backend talking to the sane daemon on localhost.

**Comment by tiriki** [comment]
How to check sane server?
scanimage -L is giving me one entry.
xsame is working.
And (some more tests):
jfreesane is communicating with my Photosmart (Wireshark catpure could be mailed on request).

**Comment by tiriki** [comment]
Interesting:
As soon as I activate the `test` backend in `/etc/sane.d/dll.conf` my Photosmart is still not showing up in
`List<SaneDevice> devices = session.listDevices();` (list still empty)
but is accessible(!) with
```java
SaneDevice device = session.getDevice("hpaio:/net/Photosmart_7520_series?ip=192.168.0.3");
device.open();
BufferedImage image = device.acquireImage();
```

As long as I deactivate the `test` backend, I get an exception on `device.open();`

**Comment by sjamesr** [comment]
Sorry for the long delay. Can you post the exception you mentioned in your last post? Also, it might help if  you include the packet dump of a simple session, e.g.

```java
SaneSession session = SaneSession.withRemoteSane(InetAddress.getByName("192.168.2.107"));
session.listDevices();
session.close();
```

**Comment by danielroehrig** [comment]
I have the same problem with an HP Deskjet2540. Although the array of found devices is empty, I can still acquire an image. But only with saned started, connected to localhost.

If I try connecting directly to the scanner, I get a connection refused exception.

**Comment by sjamesr** [comment]
@danielroehrig if you're able, can you get a packet dump for me? Something like

```bash
$ sudo tcpdump -w /tmp/out.pcap -i lo port saned
```

After running the tests, hit CTRL-C and send me `/tmp/out.pcap`. This will help me figure out if there's a config issue in saned or a bug in jfreesane. Thanks!

**Comment by Mior** [comment]
Hi there,

I had similar issue got resolved by adding saned to lp (not sure why but it helped).

Maybe it will be helpful.

**Comment by sjamesr** [comment]
As in, you added the `saned` user to the `lp` group?

**Comment by Mior** [comment]
@sjamesr yes, exactly. So guys give it a try maybe it will resolve your issues as well.

**Comment by sjamesr** [comment]
Please re-open if it persists after trying the workaround provided by @Mior.

Thank you!
