### ISSUE TITLE
Change google code formatter to break lines at 80 characters

### ISSUE THREAD

**Issue by krichter722** [sjamesr/jfreesane#45]
Currently the google code formatter not only allows lines longer than 80 characters, but enforces them (I didn't investigate exactly, but if there's a plugin which handles formatting, it should break after 80 characters).

experienced with jfreesane-0.95-39-g284b46c

**Comment by sjamesr** [comment]
The formatter enforces the Google Java style, see https://google.github.io/styleguide/javaguide.html#s4.4-column-limit stating the column limit is 100.

I've found 80 is just too small for Java.
